name: Build, SonarQube Scan, and Email

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Your existing build steps...

  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    needs: build
    if: ${{ (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged) || github.event_name == 'push' }}
    steps:
      - name: Placeholder Step
        run: echo "Placeholder step to satisfy GitHub Actions requirements"

      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Add Reviewer
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -d '{
                  "reviewers": ["triniha"]
                }'

  email:
    name: Send SonarQube Report via Email
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Your existing email steps...
