name: Auto Merge on Approval

on:
  pull_request_review:
    types:
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if review is approved
        id: check_review
        run: echo "::set-output name=approved::$(echo '${{ github.event.review.state }}' | tr '[:upper:]' '[:lower:]' )"
      
      - name: Merge Pull Request
        if: ${{ steps.check_review.outputs.approved == 'approved' }}
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
          curl -X PUT -H "Authorization: token $TOKEN" -d '{"merge_method":"merge"}' $URL
